/* Declarations generated by ty_text_extractor.py */
#pragma once
#include "include/tr_text.h"

extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
extern const _Tr_TEXT txt_input_points;
